#!/bin/bash
#SBATCH --job-name=download_data
#SBATCH --time=2:30:00
#SBATCH --priority=1000000
#SBATCH --partition=gpu
#SBATCH --ntasks=1
#SBATCH --output=download_data.log

# Run your script from the MedAI folder
cd $HOME/MedAI

# Create folders
mkdir -p raw_data/train/images
mkdir -p raw_data/train/labels
mkdir -p raw_data/validation/images
mkdir -p raw_data/validation/labels
mkdir -p raw_data/test/images

# Train part 1: 300 chest CT
wget -O raw_data/train/ribfrac-train-images-1.zip https://zenodo.org/record/3893508/files/ribfrac-train-images-1.zip
wget -O raw_data/train/ribfrac-train-labels-1.zip https://zenodo.org/record/3893508/files/ribfrac-train-labels-1.zip 
wget -O raw_data/train/ribfrac-train-info-1.csv https://zenodo.org/record/3893508/files/ribfrac-train-info-1.csv

# Train part 2: 120 chest CT
wget -O raw_data/train/ribfrac-train-images-2.zip https://zenodo.org/record/3893498/files/ribfrac-train-images-2.zip
wget -O raw_data/train/ribfrac-train-labels-2.zip https://zenodo.org/record/3893498/files/ribfrac-train-labels-2.zip 
wget -O raw_data/train/ribfrac-train-info-2.csv https://zenodo.org/record/3893498/files/ribfrac-train-info-2.csv

# Validation: 80 CT
wget -O raw_data/validation/ribfrac-val-images.zip https://zenodo.org/record/3893496/files/ribfrac-val-images.zip
wget -O raw_data/validation/ribfrac-val-labels.zip https://zenodo.org/record/3893496/files/ribfrac-val-labels.zip
wget -O raw_data/validation/ribfrac-val-info.csv https://zenodo.org/record/3893496/files/ribfrac-val-info.csv

# Test images: 160 CT
wget -O raw_data/test/images/ribfrac-test-images.zip https://zenodo.org/record/3993380/files/ribfrac-test-images.zip

# Unzip the zip files and rename folders
unzip raw_data/train/ribfrac-train-images-1.zip -d raw_data/train/ && mv raw_data/train/ribfrac-train-images-1/* raw_data/train/images
unzip raw_data/train/ribfrac-train-labels-1.zip -d raw_data/train/ && mv raw_data/train/Part1/* raw_data/train/labels
unzip raw_data/train/ribfrac-train-images-2.zip -d raw_data/train/ && mv raw_data/train/ribfrac-train-images-2/* raw_data/train/images
unzip raw_data/train/ribfrac-train-labels-2.zip -d raw_data/train/ && mv raw_data/train/Part2/* raw_data/train/labels
unzip raw_data/validation/ribfrac-val-images.zip -d raw_data/validation/ && mv raw_data/validation/ribfrac-val-images/* raw_data/validation/images
unzip raw_data/validation/ribfrac-val-labels.zip -d raw_data/validation/ && mv raw_data/validation/ribfrac-val-labels/* raw_data/validation/labels
unzip raw_data/test/ribfrac-test-images.zip -d raw_data/test/ && mv raw_data/test/ribfrac-test-images/* raw_data/test/images

# Clean up folders
rm -r raw_data/train/ribfrac-train-images-1
rm -r raw_data/train/ribfrac-train-images-2
rm -r raw_data/train/Part1
rm -r raw_data/train/Part2
rm -r raw_data/validation/ribfrac-val-images
rm -r raw_data/validation/ribfrac-val-labels
rm -r raw_data/test/ribfrac-test-images

# Clean up zip files
rm raw_data/train/ribfrac-train-images-1.zip
rm raw_data/train/ribfrac-train-labels-1.zip 
rm raw_data/train/rribfrac-train-images-2.zip
rm raw_data/train/ribfrac-train-labels-2.zip 
rm raw_data/validation/ribfrac-val-images.zip
rm raw_data/validation/ribfrac-val-labels.zip
rm raw_data/test/ribfrac-test-images.zip

# Combine the two train CSV files
tail -n +2 raw_data/train/ribfrac-train-info-2.csv >> raw_data/train/ribfrac-train-info-1.csv
mv raw_data/train/ribfrac-train-info-1.csv raw_data/train/ribfrac-train-info.csv

# Remove old CSV file
rm raw_data/train/ribfrac-train-info-2.csv

echo "Files downloaded and extracted successfully."